name: Generate Class Diagram

on:
  schedule:
    - cron: 0 15 * * *
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0
          
      - name: Update package list
        run: sudo apt-get update
        
      - name: Install PlantUML
        run: sudo apt-get install -y plantuml

      - name: Install C# UML Generator Tool
        run: dotnet tool install --global PlantUmlClassDiagramGenerator --version 1.4.0
        
      - name: Generate UML
        run: puml-gen Assets/Scripts uml.puml

      - name: Generate Image From UML
        run: plantuml uml.puml -o uml.png
        
      - name: Upload Image
        uses: actions/upload-artifact@v4
        with:
          name: uml
          path: uml.png
