name: UML Generator

on:
  push:
   branches:
    - main
  schedule:
    - cron: 0 15 * * *
  workflow_dispatch:

jobs:
  generate-uml:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v3

      - name: Install PlantUmlClassDiagramGenerator
        run: |
          git clone https://github.com/pierre3/PlantUmlClassDiagramGenerator.git
          cd PlantUmlClassDiagramGenerator
          dotnet build

      - name: Generate UML file
        run: dotnet run --project PlantUmlClassDiagramGenerator/PlantUmlClassDiagramGenerator.csproj -- ./Assets/Scripts > uml.puml
        
      - name: Upload Image
        uses: actions/upload-artifact@v4
        with:
          name: uml
          path: uml.puml
