name: Generate Class Diagram

on:
  push:
   branches:
    - main
  schedule:
    - cron: 0 15 * * *
  workflow_dispatch:

jobs:
  generate-uml:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Set up cs2plant
        run: |
          sudo apt update
          sudo apt install -y graphviz
          git clone https://github.com/ZooKong/cs2plant.git
          cd cs2plant
          pip install -r requirements.txt
          cd ..

      - name: Generate C# files to PlantUML
        run: python cs2plant/cs2plant.py Assets/Scripts -o uml.puml
          
      - name: Upload Image
        uses: actions/upload-artifact@v4
        with:
          name: uml
          path: uml.puml
