name: UML Generator

on:
  push:
   branches:
    - main
  schedule:
    - cron: 0 15 * * *
  workflow_dispatch:

jobs:
  generate-uml:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v3

      - name: Install PlantUmlClassDiagramGenerator
        run: dotnet tool install --global PlantUmlClassDiagramGenerator

      - name: Generate UML file
        run: |
          puml-gen Assets/Scripts -dir
          cd Assets/Scripts/Network
          ls
